### ISSUE TITLE
Bug: No Notification Sound when notification arrives 

### ISSUE THREAD

**Issue by Itsamanjain** [zulip/zulip-flutter#483] opened 2024-01-10 05:31 UTC
Android users are experiencing a lack of notification sound. It's essential to investigate and resolve this issue. Additionally, tagging @gnprice to verify if a similar problem exists on iPhones. Coordination is needed to ensure a comprehensive solution for both Android and iPhone users.

**Comment by Itsamanjain** [comment] 2024-01-10 05:34
after reviewing the code base of Notification.dart, I've identified that there's no existing functionality for sound. We need to implement it from scratch

**Comment by Itsamanjain** [comment] 2024-01-10 06:55
I think we can use audioplayers package to achieve this 
`import 'package:audioplayers/audioplayers.dart';
`

**Comment by Itsamanjain** [comment] 2024-01-10 17:52
I have an update after some changes in notification.dart. Now, I am getting notification sounds on my Android device. I will create a pull request when I am confident that it works on other devices as well.

**Comment by gnprice** [comment] 2024-05-03 20:58
Thanks for the report. It looks like we didn't follow up on it sooner, oops.

@Itsamanjain are you still seeing this issue? If so, I'd be glad to get more details so that we can debug. Two key pieces of information to start on that would be:
* What Android version are you seeing the issue on?
* What version of the app are you seeing the issue with? In particular, does the issue reproduce if you use the published version from the beta, or only with a version you build and run yourself?

To make the background explicit: notifications work fine for me, including on Android, including notification sounds. I don't recall hearing any other reports of this symptom, so I believe they work fine for most people. If there's a bug causing them to not work for some people, that's something we'll want to fix, but a key step toward that will be to identify where the bug appears — it's not "Android users" in general.

**Comment by gnprice** [comment] 2024-05-03 21:02
> I have an update after some changes in notification.dart. Now, I am getting notification sounds on my Android device. I will create a pull request when I am confident that it works on other devices as well.

If you still have these changes, then sharing them would be helpful for debugging too.

It looks like you made a couple of PRs (both of them around this time), #482 and #484. But #482 is from before this issue report, and at https://github.com/zulip/zulip-flutter/pull/482#issuecomment-1882454202 you say sound wasn't working even after it; and #484 is a duplicate of #482. So it doesn't seem like those represent the changes you had in mind here.

**Comment by skushagra** [comment] 2024-06-25 19:05
Hello @gnprice

If this issue is still active, I would like to work on it.

**Comment by gnprice** [comment] 2024-06-26 03:41
@skushagra See our guide for picking an issue to contribute on:
https://zulip.readthedocs.io/en/latest/contributing/contributing.html#picking-an-issue-to-work-on

**Comment by gnprice** [comment] 2024-06-26 03:43
Closing this because there isn't anything we can do to investigate without further information about the report.

@Itsamanjain if you (or anyone else reading this) see symptoms like these again, feel free to reply with more details and we can reopen.

**Closed by gnprice** 2024-06-26 03:43 UTC
Labels: a-Android, a-notifications
