### ISSUE TITLE
Android device unable to receive message notifications 

### ISSUE THREAD

**Issue by popyang** [zulip/zulip-flutter#626] opened 2024-04-22 21:37 UTC
Hi there,

I tried compiling the latest code, but notifications are not being sent to the device when new messages arrive.

Does the current version support app notifications? For example, can it show notifications in the notification bar when new messages arrive? 

I noticed Firebase Cloud Messaging (FCM) is integrated into the code. Is this feature already fully functional? 

Can we use only local notifications?

If remote notifications are the only option, what parts of the code do I need to modify to implement notification functionality? 

Thanks a lot.

**Comment by gnprice** [comment] 2024-04-26 21:25
Hello,

Yes indeed, the app does support notifications.

If you're not seeing them, the quickest way to debug might be to install the [current production app](https://zulip.com/apps/android) (from the [legacy zulip-mobile codebase](https://github.com/zulip/zulip-mobile)) — it has some [troubleshooting features](https://zulip.com/help/mobile-notifications#troubleshooting-mobile-notifications) that may help pin down what the issue is.

> notifications are not being sent to the device when new messages arrive.

Note that by default Zulip doesn't send a notification for every new message — only for DMs, @-mentions, and topics you're following. You can change that setting:
https://zulip.com/help/mobile-notifications

**Comment by gnprice** [comment] 2024-05-09 19:36
Closing to get this out of our queue, since it's not actionable for us at present. If you're still seeing this issue and interested in investigating it, please feel free to reply with more information and I'll be happy to re-open.

**Closed by gnprice** 2024-05-09 19:36 UTC
Labels: a-Android, a-notifications
