### ISSUE TITLE
Tappable links' touch target can extend through whitespace

### ISSUE THREAD

**Issue by chrisbobbe** [zulip/zulip-flutter#214] opened 2023-07-07 20:33 UTC
If you have a short paragraph ending in a link, the space between the link and the end margin is also tappable. Shown here in the app as built for macOS, so you can see the tappable area when the cursor changes on hover:

![Jul-07-2023 13-32-51](https://github.com/zulip/zulip-flutter/assets/22248748/d790c20b-0218-4696-97dd-2310263bb3da)

**Comment by gnprice** [comment] 2023-07-07 20:42
Wacky! Thanks for the report. Copying what I said at https://github.com/zulip/zulip-flutter/pull/204#issuecomment-1624225216 :

A variation on that scenario would be when the paragraph wraps over multiple lines, and the last line is short and ends with a link. I'd guess the same bug would reproduce there.

It sounds like the last TextSpan's `recognizer` is inappropriately being applied through the end of the line when the TextSpan visually doesn't extend that far. So this may be an upstream Flutter bug.

**Comment by chrisbobbe** [comment] 2023-07-07 20:46
Ah indeed; the "short" part of "[i]f you have a short paragraph ending in a link" is not required. 🙂

**Comment by gnprice** [comment] 2024-01-04 02:05
It looks like this was the following upstream issue:
* https://github.com/flutter/flutter/issues/131435

That was closed by https://github.com/flutter/flutter/pull/140621 (the same upstream change that induced #475, which is why I came across it). So it's likely this issue no longer reproduces. If not, we can close it.

**Closed** 2024-01-04 08:24 UTC
Labels: a-content
