### ISSUE TITLE
Visual glitches when scrolling on Fairphone 3+

### ISSUE THREAD

**Issue by j-maas** [zulip/zulip-flutter#941] opened 2024-09-13 19:22 UTC
I'm using Android on a Fairphone 3+. When I scroll in the Zulip Beta v0.0.19, I see some weird artifacts.

It doesn't seem to impact functionality, it's just visually annoying.

Curiously, when I try to record my screen on the phone, the glitches don't appear. As soon as the screen recording is stopped, they appear again when scrolling.

I was however able to capture some screenshots of what it looks like. These are only visible for a frame each, but while scrolling there are a lot of such glitches.

| Normal | Scrolling | Scrolling more |
|---------|-----------|-----------------|
|![Screenshot_20240913-210444.png](https://github.com/user-attachments/assets/7dc7071b-d354-4f34-96c3-c0b271e0915f)|![Screenshot_20240913-210446.png](https://github.com/user-attachments/assets/dce61a46-6568-42fe-a85b-19e13e201635)|![Screenshot_20240913-210450.png](https://github.com/user-attachments/assets/e9d70245-e448-4adf-882f-a107143acbdc)|

**Comment by gnprice** [comment] 2024-09-13 21:30
Interesting, thanks for the report! I don't think we've seen a symptom like that before in this app.

Given these symptoms, I think the issue has to be either in the Flutter engine, or your device's graphics drivers (or I guess possibly the graphics hardware). Flutter is in the late stages of a rewrite of their rendering engine, called [Impeller](https://docs.flutter.dev/perf/impeller); Impeller is currently in beta on Android, and we're using it in our beta. Being in beta means Impeller still has more bugs than it will when stable, and also that its authors are still busy discovering bugs in a wide variety of devices' graphics drivers, and adding workarounds for those.

Looking in the upstream tracker, here's one open issue with a similar flavor:
* https://github.com/flutter/flutter/issues/153762

I think the Flutter engine developers will probably be able to resolve this issue pretty quickly once they can reproduce it. I'll file an issue upstream and see what further information they ask for.

**Comment by gnprice** [comment] 2024-09-13 21:33
Do you happen to have the Android developer tools set up on your machine?

If so, then one thing you can do that's very likely to be helpful is to get via `adb logcat` the logs that are emitted while reproducing the issue. Some details here on how to conveniently use `adb logcat`:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/adb.20logcat/near/1929345

(If not, though, don't worry about it.)

**Comment by gnprice** [comment] 2024-09-13 22:00
Filed:
* https://github.com/flutter/flutter/issues/155185

**Comment by gnprice** [comment] 2024-10-29 20:54
That upstream issue was closed today, with a change in the Flutter engine so that Flutter will fall back to an older graphics system when it sees the GPU that's found in that device. That should resolve this problem.

Thanks again @j-maas for the report!

Closing this issue because it's fixed upstream and I expect we'll update to a Flutter with the fix before our next beta release. (Also being closed means I'll naturally look back at it when preparing the next release, which will give me a prompt to confirm that we did update.)

**Closed by gnprice** 2024-10-29 20:54 UTC
Labels: a-Android

**Comment by gnprice** [comment] 2024-11-13 01:42
> it's fixed upstream and I expect we'll update to a Flutter with the fix before our next beta release

FTR, that update happened in 163ea280d / #1057.

**Comment by gnprice** [comment] 2024-11-14 00:15
And today's beta release v0.0.21 has that update. @j-maas please try it out when convenient, and let us know whether that indeed fixes the problem. Thanks again for the report!

**Comment by gnprice** [comment] 2024-11-15 20:00
Huh! Thanks for the update.

The upstream change that was aimed at fixing this happened in flutter/engine@999797a2f690, which was pulled in by flutter/flutter@47318592d1dd00a94d88a2f8060b28b826911c22, which in turn only entered our tree in the commit I mentioned above. We released 0.0.20 a few weeks before that upstream change; it used Flutter 3.26.0-1.0.pre.249, aka flutter/flutter@ead6b0d17c893109b9424aaf116a74295472cc73.

So I guess some earlier change already fixed the glitch. The behavior may be different again with 0.0.21, though — that one should disable Flutter's use of its Vulcan graphics backend on your GPU, falling back to GLES. I'm therefore curious how 0.0.21 goes too.

**Comment by gnprice** [comment] 2024-11-15 20:01
(I think 0.0.21 became available for you about a half-hour after your comment above, from the timestamps I see in the Play Console. It takes a bit for them to review it, even for apps in beta channels.)

**Comment by j-maas** [comment] 2024-11-16 09:56
I just noticed that it's glitch-free and smooth. So I checked the version and it's v0.0.21!

It's flawless now. Thanks for taking the time to explain everything to me and keeping me updated!

**Comment by j-maas** [comment] 2024-11-16 09:57
I just noticed that it's glitch-free and smooth. So I checked the version and it's v0.0.21!

It's flawless now. Thanks for taking the time to explain everything to me and keeping me updated!

**Comment by gnprice** [comment] 2024-11-20 03:43
Great, glad to hear it. Thanks for the update (and the original report)!
